// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockReadinessStore creates a new instance of MockReadinessStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReadinessStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReadinessStore {
	mock := &MockReadinessStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReadinessStore is an autogenerated mock type for the readinessStore type
type MockReadinessStore struct {
	mock.Mock
}

type MockReadinessStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReadinessStore) EXPECT() *MockReadinessStore_Expecter {
	return &MockReadinessStore_Expecter{mock: &_m.Mock}
}

// IsClosed provides a mock function for the type MockReadinessStore
func (_mock *MockReadinessStore) IsClosed() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsClosed")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockReadinessStore_IsClosed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsClosed'
type MockReadinessStore_IsClosed_Call struct {
	*mock.Call
}

// IsClosed is a helper method to define mock.On call
func (_e *MockReadinessStore_Expecter) IsClosed() *MockReadinessStore_IsClosed_Call {
	return &MockReadinessStore_IsClosed_Call{Call: _e.mock.On("IsClosed")}
}

func (_c *MockReadinessStore_IsClosed_Call) Run(run func()) *MockReadinessStore_IsClosed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReadinessStore_IsClosed_Call) Return(b bool) *MockReadinessStore_IsClosed_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockReadinessStore_IsClosed_Call) RunAndReturn(run func() bool) *MockReadinessStore_IsClosed_Call {
	_c.Call.Return(run)
	return _c
}
