http:
  port: "8080"
  read_timeout_in_second: 5
  write_timeout_in_second: 120
  idle_timeout_in_second: 120
  shutdown_timeout_in_second: 5
  max_body_size_in_bytes: 1048576

logger:
  level: debug
  sampling_initial: 100
  sampling_thereafter: 100

middleware:
  request_log:
    skip_paths: ["/health"]
    log_query: true
    query_allowlist: ["page", "limit", "cursor"]

sqlite:
  dsn: "lux.db"

badger:
  dir: "lux"
