// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/Chandra179/lux/server/internal/example"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStore is an autogenerated mock type for the store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// CreateExample provides a mock function for the type MockStore
func (_mock *MockStore) CreateExample(ctx context.Context, name string) (*example.Example, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateExample")
	}

	var r0 *example.Example
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*example.Example, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *example.Example); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*example.Example)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStore_CreateExample_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExample'
type MockStore_CreateExample_Call struct {
	*mock.Call
}

// CreateExample is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockStore_Expecter) CreateExample(ctx any, name any) *MockStore_CreateExample_Call {
	return &MockStore_CreateExample_Call{Call: _e.mock.On("CreateExample", ctx, name)}
}

func (_c *MockStore_CreateExample_Call) Run(run func(ctx context.Context, name string)) *MockStore_CreateExample_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStore_CreateExample_Call) Return(example1 *example.Example, err error) *MockStore_CreateExample_Call {
	_c.Call.Return(example1, err)
	return _c
}

func (_c *MockStore_CreateExample_Call) RunAndReturn(run func(ctx context.Context, name string) (*example.Example, error)) *MockStore_CreateExample_Call {
	_c.Call.Return(run)
	return _c
}
